description: <Job Description>    # Optional
service: <API Service Name>
versions:
  - <Version>
tags:
  - <Tag Name>
jobs:
  - name: <Sub job 1 to be run>
    description: <individual job description>       # Optional
    endpoint: <API endpoint>
    operation: <HTTP operation>
    path_parameters:                                # Required when path parameter present in endpoint
      <Path Param name>: <value>
    query_parameters:                               # Optional
      <Query Param name> : <value>
    polling:                                        # Optional
      interval: <Polling Interval Value in seconds>
      timeout: <Polling Timeout Value in seconds>
    env_vars:           							# Optional
      <Key>: <Value>
    request_body: |                                 # Optional
      <request body to be sent in request>
    storage_vars:       # Optional
      <Key>: <Value>    # Value should start with "$response" and comply with "dot" notation
    filter:             # Optional
      - path: <Path to filter>
        type: <Type>                    # enum - [string, array, object]
        regex: <Boolean value>          # Optional, to be used with "string" only
        value: <Value to be filtered>   # Optional
        size: <Size>                    # Optional
    response:
      <response status>: |
        <data to be matched against the response>
  - $ref: <Path to template file>
    args:               # Optional
      <Key>: <Value>